# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-10-30T07:02:44+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class CardRequest(BaseModel):
    number: str = Field(..., description="Credit card number")


class Scheme(Enum):
    visa = "visa"
    amex = "amex"
    mastercard = "mastercard"


class Message(Enum):
    OK = "OK"


class CardValidation(BaseModel):
    valid: bool = Field(..., description="Whether the card number passes Luhn check")
    scheme: Scheme = Field(..., description="Card scheme")
    message: Message = Field(..., description="Status message")


class ErrorResponse(BaseModel):
    code: str = Field(..., description="Error code")
    error_message: str = Field(..., description="Detailed error message")
